### PR TITLE
React todo app

### PR DESCRIPTION
**Pull request by d2ndjim**
- Learned how to work with React app
- Implemented todo app using class components 
- Implemented todo app using functional components
- Used SVG icons in the todo app
- Added hamburger menu to the project
- Used react routing in the project

### CODE REVIEW

**Review by Yazino12 — CHANGES_REQUESTED** [review]
### Hi @d2ndjim,

You did a great job so far 👏🏼 👏🏼
There are some issues that you still need to implement as per the requirements of the project!

### To highlight 💪🏻

- Descriptive readme file. ✔️ 
- Meaningful commit messages. ✔️ 
- Good quality code. ✔️ 



## STATUS: CHANGES REQUESTED  ♻️ 
_Please Check the comments under the review and make all required changes_

- [Required] Please, Linter should be set up correctly for this repository. Linter result should be green. AKA: Linter should report NO errors. There should be no custom changes to the linter config (as an attempt to cheat linter error reports).

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- [Optional] Please, make sure that you use the correct Gitflow. [Gitflow Workflow](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow). Branch should have a name of a feature or action (e.g. 'created_sidebar' or 'added_comments_section'). Pull request is made from the feature branch into the dev branch.


Cheers and Happy coding!👏👏👏 💻  
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me @Yazino12 when you comment so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------

**Comment by d2ndjim** [comment]
Thank you for the thorough review @Yazino12. I opted against using linters in the project as the version of react used for the tutorial is slightly outdated and the react linters for the current version keeps throwing errors.

**Comment by Yazino12** [comment]
Hello, again @d2ndjim,

I can see what you mean, even-though I would suggest you use `npx eslint . --fix` and try to debug the messages you get.
I did the same, just debugging one error message at a time.

**Comment by d2ndjim** [comment]
You used only functional components. I have both functional and class
components if you check my project.

**Review by Yazino12 — APPROVED** [review]
### Hi @d2ndjim,

I see the reason you didn't use Linters in your project as you have both Functional and Class components in your repository.



## STATUS: APPROVED ✔️ ✔️ ✔️ 
_Please Check the comments under the review and make all required changes_

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- [Optional] Please, you can still use Linters and just ignore the Class component directory.


Well done 🎉🎉🎉

**Pull request merged**
